config/routes.rb
Rails.application.routes.draw do
  root 'puzzles#index'
  
  resources :puzzles do
    collection do
	  get 'seed'
	end
	member do
	  get 'import'
	  get 'results' # Temporaire : affiche le resultat pour tous les players connus 
	end
  end
  resources :players do
    collection do
	  get 'search'
	  get 'save'
	  get 'refresh'
	  get 'isRefreshPending'
	  get 'ranking'
	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  has_many :achievement_player, dependent: :destroy
  belongs_to :puzzle, optional: true
  belongs_to :language, optional: true
  
  # This comes from a CG API flaw, where puzzle_id always equals to 0...
  # We should then look for textId=~/PZ_(\d+)P_P$puzzleId$/
  def compute_puzzle_id
	if groups = /PZ_(\d+)P_P(\d+)/.match(text_id)
		cgid = groups[2]
	else
	    return
	end
	# Another error from CG
	if not /PZ_(\d+)P_P53$/.match(text_id).nil?
		cgid = 55
	end
	if not /PZ_(\d+)P_P52$/.match(text_id).nil?
		cgid = 54
	end
	if not /PZ_(\d+)P_P3$/.match(text_id).nil?
		cgid = 121
	end
	self.update_attributes puzzle_id: Puzzle.find_by(cgid: cgid).id
  end
end

app/models/achievement_player.rb
class AchievementPlayer < ApplicationRecord
	belongs_to :achievement
	belongs_to :player
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true  
end

app/models/language.rb
class Language < ApplicationRecord
	has_many :achievements
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
  has_many :achievement
  has_many :results
  
  scope :without_community, -> { where("level <> ?", "community") }
  scope :by_level, ->(level) { where(:level => level) }
  scope :order_by_level, -> { order(:level) }
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :player
  belongs_to :puzzle
  belongs_to :language
  
  validates :player, presence: true
  validates :puzzle, presence: true
  validates :language, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  before_action :set_puzzle, only: [:show, :edit, :update, :destroy, :import, :results]

  # GET /puzzles
  # GET /puzzles.json
  def index
    @puzzles = Puzzle.all
	level = params[:level] || 'easy'
	if level=='easy' or level=='medium' or level=='hard' or level=='expert'
		@level_has_achievements = true
	end
	@puzzles = @puzzles.by_level(level)
	if params[:pid]
		@pids = params[:pid].split(',')
		@results = Array.new
		@players = Array.new
		playerIds = Array.new # id's (not cgid's) of Players
		for pid in @pids
			player = Player.find_by(cgid: pid)
			playerIds.push player.id
			# player n'est pas NIL, car le pid vient d'une recherche qui doit avoir sauvé le player en base
			player.last_displayed = Time.now
			if player.mustRefresh
				player.refresh_pending = true
				player.save				
				ResultRefreshJob.perform_later(player)
			end
			player.save!
			@players.push (player)
			@results.push( Result.where(player: player).joins(:puzzle).where("puzzles.level = ?", level) )
		end
		@solvedLangs = @results.flatten.map{|r| r.language_id}.uniq
		@results = @results
			.flatten
			.group_by {|r| "#{r.player.cgid}:#{r.puzzle_id}:#{r.language_id}"}
		@languages = Language.all.to_a.keep_if{|l| @solvedLangs.include?(l.id)}
		@achpl = AchievementPlayer.where(player_id: playerIds)
		#@debug=1
	end
  end

  # GET /puzzles/seed
  def seed
    text = File.read(Rails.root.join('app','models','seed','findGamePuzzleProgress.json'))
	json = JSON.parse(text)
	json["success"].each do |p|
	  if not Puzzle.exists?( :cgid => p["id"] )
		  new_puzzle = Puzzle.new
		  new_puzzle.cgid=p["id"]
		  new_puzzle.title=p["title"]
		  new_puzzle.description=p["description"]
		  new_puzzle.detailsPageUrl=p["detailsPageUrl"]
		  new_puzzle.level=p["level"]
		  new_puzzle.prettyId=p["prettyId"]
		  new_puzzle.solvedCount=p["solvedCount"]
		  new_puzzle.puzzleType=p["type"]
		  new_puzzle.leaderboardId=p["puzzleLeaderboardId"]
		  new_puzzle.achievementCount=p["achievementCount"]
		  new_puzzle.save
	  end
	end
	redirect_to puzzles_url
  end

  # GET /puzzles/1
  # GET /puzzles/1.json
  def show
  end

  # GET /puzzles/new
  def new
    @puzzle = Puzzle.new
  end

  # GET /puzzles/1/edit
  def edit
  end
  
  # GET /puzzles/1/results
  def results
	api = CodingameApi.new
	@results = Player.all.map { |p| [p.pseudo , api.puzzle_player_langages(@puzzle,p)] }.to_h
  end

  # GET /puzzles/1/import
  def import
	api = CodingameApi.new
	response = api.puzzle_leaderboard @puzzle
	if response.message=="OK"
		result = JSON.parse( response.body )
		@test = result['success']['users']
	else
		@test = [ "CG API Error" ]
	end
  end

  # POST /puzzles
  # POST /puzzles.json
  def create
    @puzzle = Puzzle.new(puzzle_params)

    respond_to do |format|
      if @puzzle.save
        format.html { redirect_to @puzzle, notice: 'Puzzle was successfully created.' }
        format.json { render :show, status: :created, location: @puzzle }
      else
        format.html { render :new }
        format.json { render json: @puzzle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puzzles/1
  # PATCH/PUT /puzzles/1.json
  def update
    respond_to do |format|
      if @puzzle.update(puzzle_params)
        format.html { redirect_to @puzzle, notice: 'Puzzle was successfully updated.' }
        format.json { render :show, status: :ok, location: @puzzle }
      else
        format.html { render :edit }
        format.json { render json: @puzzle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puzzles/1
  # DELETE /puzzles/1.json
  def destroy
    @puzzle.destroy
    respond_to do |format|
      format.html { redirect_to puzzles_url, notice: 'Puzzle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puzzle
      @puzzle = Puzzle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puzzle_params
      params.require(:puzzle).permit(:cgid, :title, :description, :detailsPageUrl, :level, :prettyId, :solvedCount, :type, :achievementCount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def posOrString(val,str)
		if val > 0
			val
		else
			str
		end
	end

	# Extrait d'une liste d'achievement celui qui a la plus grande valeur de "progress_max" inférieure à value
	def getBestAchievement(list, value)
		list.select{ |ach| ach.progress_max <= value }
			.sort{ |a,b| a.progress_max <=> b.progress_max }
			.last
	end
	
	# URL to a CG static file
	def staticFileFromId(id)
		"https://static.codingame.com/servlet/fileservlet?id=#{ id }"
	end
end

app/helpers/players_helper.rb
module PlayersHelper


end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CG puzzles stats</title>
	
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	<script src="/js/jquery.query-object.js"></script>

	<link rel="stylesheet" href="/css/styles.css">

	</head>
  <body>
  
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89424143-1', 'auto');
  ga('send', 'pageview');

</script>  

		<!--       GITHUB LINK      -->
		
  <a href="https://github.com/Orabig/CGPuzzleStats" target="_new" class="github-corner" aria-label="View source on Github"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#337ab7; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>

  <div class="row">
	<div class="col-md-1"> </div>
	<div class="col-md-10">

		<!--    TITRE   + links  -->
		<div id="title">
		  <h3><a href="/<%= 
		  
			if @cgids
				'?level=easy&pid='+@cgids.join(',')
			end
		  
		  %>" class="btn"><span class="glyphicon glyphicon-home"/></a> CodinGame Puzzle Status</h3>
		</div>
		<div id="links">
		<a href="http://cgstats.magusgeek.com/">CG Multi Stats</a> - <a href="http://apps.rezonux.com/codingame/">Royale tool</a>
		</div>
		<br clear="all"/>
		
    <%= yield %>
	</div>
</div>
</body>

app/views/players/_form.html.erb
<%= form_for(player) do |f| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cgid %>
    <%= f.number_field :cgid %>
  </div>

  <div class="field">
    <%= f.label :pseudo %>
    <%= f.text_field :pseudo %>
  </div>

  <div class="field">
    <%= f.label :level %>
    <%= f.number_field :level %>
  </div>

  <div class="field">
    <%= f.label :rank %>
    <%= f.number_field :rank %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>
<pre><%= @refresh_started %>/<%= @refresh_pending %></pre>
<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Cgid</th>
      <th>Pseudo</th>
      <th>Level</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.cgid %></td>
        <td><%= player.pseudo %></td>
        <td><%= player.level %></td>
        <td><%= player.rank %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>
<%= form_tag( {controller: "players", action: "search"}, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/ranking.html.erb
<p id="notice"><%= notice %></p>
<table id="ranking" class="table table-striped">
  <thead>
    <tr>
	  <th class="titre" colspan="3">100% complete solo puzzles</th>
      <th rowspan="2" class="r expert"><div></div>Expert</th>
      <th rowspan="2" class="r hard"><div></div>Hard</th>
      <th rowspan="2" class="r medium"><div></div>Medium</th>
      <th rowspan="2" class="r easy"><div></div>Easy</th>
	</tr>
    <tr>
      <th>CG rank</th>
      <th>Player</th>
      <th>Level</th>
    </tr>
  </thead>

  <tbody>
    <% @players.sort_by{ |p| @scores[p.id][:score] }.reverse.each do |player| %>
      <tr>
        <td>#<%= player.rank %></td>
        <td><%= player.pseudo %></td>
        <td>Lvl <%= player.level %></td>
        <td class="r expert"><%= posOrString( @scores[player.id][:expert] , '-' )  %></td>
        <td class="r hard"><%= posOrString( @scores[player.id][:hard] , '-' )  %></td>
        <td class="r medium"><%= posOrString( @scores[player.id][:medium] , '-' )  %></td>
        <td class="r easy"><%= posOrString( @scores[player.id][:easy] , '-' ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>





<table id="languages" class="table table-striped">
  <thead>
    <tr>
	  <th class="titre">Prefered languages</th>
      <th rowspan="2" class="r"><div></div>#1</th>
      <th rowspan="2" class="r"><div></div>#2</th>
      <th rowspan="2" class="r"><div></div>#3</th>
      <th rowspan="2" class="r"><div></div>#4</th>
      <th rowspan="2" class="r"><div></div>#5</th>
	</tr>
    <tr>
      <th>Player</th>
    </tr>
  </thead>

  <tbody>
    <% @players.sort_by{ |p| @scores[p.id][:score] }.reverse.each do |player| %>
      <tr>
        <td><%= player.pseudo %></td>
		<%
		for i in 0..4
			# Most used language
			lang=@langs[player.id].keys.at( i )
			if not lang.nil?
				# How many solution in this language
				count=@langs[player.id][lang]
				# The best achievement for this
				ach=getBestAchievement(@achievements[lang], count)
				if not ach.nil?
				%>
				<td class="r"><div 
					class="level-<%= ach.level %>" 
					style="background-image: url(<%= staticFileFromId( ach.image_binary_id ) %>);" 
					data-toggle="tooltip" title="<%= ach.description %>"></div>
				<%= count %> puzzles</td>
				<%
				end
			end
		end
		%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Search result</h1>

<table>
  <thead>
    <tr>
      <th>CGID</th>
      <th>Country</th>
      <th>Rank</th>
      <th>Level</th>
      <th>Pseudo</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player["codingamer"]["userId"] %></td>
        <td><%= player["codingamer"]["countryId"] %></td>
        <td>#<%= player["rank"] %></td>
        <td><%= player["codingamer"]["level"] %></td>
        <td><%= player["pseudo"] %></td>
        <td><%= link_to "Save", save_players_url(
			cgid: player["codingamer"]["userId"], 
			rank: player["rank"],
			level: player["codingamer"]["level"],
			pseudo: player["pseudo"]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cgid:</strong>
  <%= @player.cgid %>
</p>

<p>
  <strong>Pseudo:</strong>
  <%= @player.pseudo %>
</p>

<p>
  <strong>Level:</strong>
  <%= @player.level %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @player.rank %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/puzzles/_form.html.erb
<%= form_for(puzzle) do |f| %>
  <% if puzzle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(puzzle.errors.count, "error") %> prohibited this puzzle from being saved:</h2>

      <ul>
      <% puzzle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cgid %>
    <%= f.number_field :cgid %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :detailsPageUrl %>
    <%= f.text_field :detailsPageUrl %>
  </div>

  <div class="field">
    <%= f.label :level %>
    <%= f.text_field :level %>
  </div>

  <div class="field">
    <%= f.label :prettyId %>
    <%= f.text_field :prettyId %>
  </div>

  <div class="field">
    <%= f.label :leaderboardId %>
    <%= f.text_field :leaderboardId %>
  </div>

  <div class="field">
    <%= f.label :solvedCount %>
    <%= f.number_field :solvedCount %>
  </div>

  <div class="field">
    <%= f.label :puzzleType %>
    <%= f.text_field :puzzleType %>
  </div>

  <div class="field">
    <%= f.label :achievementCount %>
    <%= f.number_field :achievementCount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/puzzles/edit.html.erb
<h1>Editing Puzzle</h1>

<%= render 'form', puzzle: @puzzle %>

<%= link_to 'Show', @puzzle %> |
<%= link_to 'Back', puzzles_path %>

app/views/puzzles/import.html.erb
<h1>Loaderboard Puzzle : '<%= @puzzle.title %>'</h1>

<%= @test %>
<br>
<%= link_to 'Back', puzzles_path %>

app/views/puzzles/new.html.erb
<h1>New Puzzle</h1>

<%= render 'form', puzzle: @puzzle %>

<%= link_to 'Back', puzzles_path %>

app/views/puzzles/results.html.erb
<h1>Loaderboard Puzzle : '<%= @puzzle.title %>'</h1>

<% @langs=@results.fetch(@results.keys.first).map{|r| r['id']} %>

<table>

	<tr>
		<th>Pseudo</th>
		<% @langs.each do |lang| %>
			<th><%= lang %></th>
		<% end %>
	</tr>
	
<% @results.each_pair do |playerPseudo, results| %>
	<tr>
		<th><%= playerPseudo %></th>
		<% i=0 %>
		<% @langs.each do |lang| %>
			<td><%= results[i]["solved"] ? "X" : "" %></td>
			<% i=i+1 %>
		<% end %>
	</tr>
<% end %>

</table>
<br>
<%= link_to 'Back', puzzles_path %>

app/views/puzzles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cgid:</strong>
  <%= @puzzle.cgid %>
</p>

<p>
  <strong>Title:</strong>
  <%= @puzzle.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @puzzle.description %>
</p>

<p>
  <strong>Detailspageurl:</strong>
  <%= @puzzle.detailsPageUrl %>
</p>

<p>
  <strong>Level:</strong>
  <%= @puzzle.level %>
</p>

<p>
  <strong>Prettyid:</strong>
  <%= @puzzle.prettyId %>
</p>

<p>
  <strong>leaderboardId:</strong>
  <%= @puzzle.leaderboardId %>
</p>

<p>
  <strong>Solvedcount:</strong>
  <%= @puzzle.solvedCount %>
</p>

<p>
  <strong>Type:</strong>
  <%= @puzzle.puzzleType %>
</p>

<p>
  <strong>Achievementcount:</strong>
  <%= @puzzle.achievementCount %>
</p>

<%= link_to 'Edit', edit_puzzle_path(@puzzle) %> |
<%= link_to 'Back', puzzles_path %>